kitchen_app/api/urls.py
from django.conf.urls import patterns, url

from kitchen_app.api import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^create_request$', views.create_request, name='create_request'),
    url(r'^cancel_request$', views.cancel_request, name='cancel_request'),
    url(r'^ack_request$', views.ack_request, name='ack_request'),
    url(r'^fulfill_request$', views.fulfill_request, name='fulfill_request'),
    url(r'^current_requests$', views.current_requests, name='current_requests'),
    url(r'^available_items$', views.available_items, name='available_items'),
    url(r'^clear_database$', views.clear_database, name='clear_database'),
    url(r'^kitchen_requests$', views.kitchen_requests, name='kitchen_requests'),
    url(r'^add_item', views.add_item, name='add_item'),
    url(r'^remove_item', views.remove_item, name='remove_item'),
    url(r'^bulk_edit', views.bulk_edit, name='bulk_edit'),
    url(r'^populate_db', views.populate_db, name='populate_db'),
)

kitchen_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from kitchen_app.api import urls as api_urls
from kitchen_app.web_ui import urls as web_ui_urls
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(api_urls, namespace='api')),
    url(r'^', include(web_ui_urls))
]

kitchen_app/web_ui/urls.py
from django.conf.urls import patterns, url

from kitchen_app.web_ui import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)

kitchen_app/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
import models

kitchen_app/models/employee.py
# -*- coding: utf-8 -*-
from django.db import models


class Employee(models.Model):
    last_name = models.CharField(max_length=32)
    first_name = models.CharField(max_length=32)
    username = models.CharField(max_length=32, unique=True)

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    class Meta:
        db_table = 'employee'

kitchen_app/models/item.py
# coding -*- utf-8 -*-
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        db_table = 'item'

kitchen_app/models/item_location.py
# -*- coding utf-8 -*-
from django.db import models

from item import Item

class ItemLocation(models.Model):
    floor = models.PositiveSmallIntegerField(db_index=True)
    item = models.ForeignKey(Item)

    class Meta:
        db_table = 'item_location'
        unique_together = ('floor', 'item')

kitchen_app/models/request.py
# -*- coding: utf-8 -*-
from django.db import models


from employee import Employee
from item_location import ItemLocation


class Request(models.Model):
    requester = models.ForeignKey(Employee)
    request_time = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(ItemLocation)
    status = models.PositiveSmallIntegerField(default=0)
    employee_location = models.CharField(max_length=200, default='Unspecified')

    class Meta:
        db_table = 'request'

kitchen_app/api/views.py
import json

from datetime import datetime
from django.core import serializers
from django.http import HttpResponse
from django.http import HttpResponseNotAllowed
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt


from kitchen_app.models import Item
from kitchen_app.models import Request as ItemRequest
from kitchen_app.models import ItemLocation
from kitchen_app.models import Employee
from kitchen_app.api.helpers import find_user_location
from kitchen_app.api.helpers import create_item
from kitchen_app.api.helpers import delete_item
from kitchen_app.api.helpers import create_serialized_response
from kitchen_app.api.helpers import populate_database


ok_resp = HttpResponse(json.dumps({'ok' : 'ok'}))
bad_resp = HttpResponse(json.dumps({'ok' : 'no'}))

YELP_LOVE_URL = 'https://yelplove.appspot.com/'


def index(request):
    return HttpResponse("Main API page")


@csrf_exempt
def create_request(request):
	'''
	add a new item request to the Request table
	'''
	if request.method == 'POST':
		username = request.POST['name']
		# check to see if requester has specified an override location
		if 'user_location' in request.POST:
			user_location = request.POST['user_location']
		else:
			# no location specified, find out where the user sits
			user_location = find_user_location(username)
		# create the new item	
		
		new_item = create_item(
			username,
			str(datetime.now()),
			int(request.POST['item_id']),
			user_location)
		if new_item is None:
			return bad_resp
		# store it into the database
		new_item.save()
        return redirect('kitchen_app.web_ui.views.index')
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def cancel_request(request):
	if request.method == 'POST':
		request_id = request.POST['request_id']
		if delete_item(request_id):
			return ok_resp
		return bad_resp
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def ack_request(request):
	if request.method == 'POST':
		request_id = request.POST['request_id']
		ack_item = ItemRequest.objects.get(id=request_id)
		ack_item.status = 1
		ack_item.save()
		delivery_person = ''
		if 'delivery_person' in request.POST:
			delivery_person = request.POST['delivery_person']
		# let them know somehow


		return ok_resp
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def fulfill_request(request):
	if request.method == 'POST':
		request_id = request.POST['request_id']
		if not delete_item(request_id):
			return bad_resp
		return_url = YELP_LOVE_URL
		if 'delivery_person' in request.POST:
			delivery_person = request.POST['delivery_person']
			return_url += '?recipient=%s' % delivery_person
		return HttpResponse(json.dumps({'url': return_url}))
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def current_requests(request):
	if request.method == 'POST':
		name = request.POST['name']
		employee = Employee.objects.get(username=name)
		requests = ItemRequest.objects.filter(requester=employee)
		return create_serialized_response(requests)
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def kitchen_requests(request):
	if request.method == 'POST':
		# find the snacks on the floor
		floor = int(request.POST['floor'])
		requests = ItemRequest.objects.filter(item__floor=floor)
		return_value = []
		for req in requests:
			requester = req.requester
			req_dict = {}
			req_dict['requester'] = requester.username
			req_dict['status'] = req.status
			req_dict['item'] = req.item.item.name
			req_dict['employee_location'] = req.employee_location
			req_dict['request_time'] = str(req.request_time)
			return_value.append(req_dict)
		return HttpResponse(json.dumps(return_value))
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def available_items(request):
	if request.method == 'POST':
		floor = request.POST['floor']
		items = ItemLocation.objects.filter(floor=floor)
		return_value = []
		for item in items:
			snack_info = item.item
			item_dict = {}
			item_dict['id'] = item.id
			item_dict['name'] = snack_info.name
			return_value.append(item_dict)
		return HttpResponse(json.dumps(return_value))
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def clear_database(request):
	if request.method == 'POST':
		ItemRequest.objects.all().delete()
		return ok_resp
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def add_item(request):
	if request.method == 'POST':
		floor = request.POST['floor']
		item_id = request.POST['item_id']
		item = Item.objects.get(id=item_id)
		# see if this item already exists
		item_location = ItemLocation.objects.filter(floor=floor).filter(item=item)
		if not item_location:
			item_location = ItemLocation(floor=floor, item=item)
			item_location.save()
			return ok_resp
		else:
			return bad_resp
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def remove_item(request):
	if request.method == 'POST':
		floor = request.POST['floor']
		item_id = request.POST['item_id']
		item = Item.objects.get(id=item_id)
		# see if this item actually exists
		item_location = ItemLocation.objects.filter(floor=floor).filter(item=item)
		if item_location:
			item_location.delete()
			return ok_resp
		else:
			return bad_resp
	return HttpResponseNotAllowed(['POST'])


@csrf_exempt
def bulk_edit(request):
	if request.method == 'POST':
		floor = request.POST['floor']
		available_items = request.POST['available_items']
		# find the diffs
		# first delete all that isn't in this new set
		to_delete = ItemLocation.objects \
			.filter(floor=floor) \
			.exclude(item__in=available_items)
		to_delete.delete()
		# now find out which isn't in there
		# grab all the ones already on the floor
		current_items = ItemLocation.objects.filter(floor=floor)
		current_ids = []
		for current_item in current_items:
			current_ids.append(current_item.item)
		# insert the new items
		for available_item in available_items:
			if available_item not in current_ids:
				ItemLocation(floor=floor, item=available_item).save()

		return ok_resp
		
	return HttpResponseNotAllowed(['POST'])

@csrf_exempt
def populate_db(request):
	populate_database()
	return ok_resp

kitchen_app/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("yo")

kitchen_app/web_ui/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render

from kitchen_app.models.item import Item
from kitchen_app.models.request import Request


def index(request):
    context = {
        'floor_options': range(2,15),
        'items': [(item.id, item.name) for item in Item.objects.all()],
        'active_requests': Request.objects.filter(status=0).order_by('-request_time'),
    }
    return render(request, 'index.html', context)

kitchen_app/templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,700,900,300' rel='stylesheet' type='text/css'>
        <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}">
        <title>FeedMe</title>
    </head>
    <body>
        <!-- Fixed navbar -->
        <div class="header">
            <img class="logo center" src="{% static "images/logo.png" %}">
        </div>
        <div class="header-extension">
            <form id="request_form" action="{% url 'api:create_request' %}" method="post">
                {% csrf_token %}
                <div class="input-container">
                    <input name="name" class="order-name center" type="text" placeholder="Enter username here">
                </div>
                <div class="input-container">
                    <input name="user_location" class="order-name center" type="text" placeholder="Where are you located?">
                </div>
                <div class="input-container">
                    <select class="order-floor center">
                        <option>Select a floor where your snack is located</option>
                        {% for i in floor_options %}
                            <option>{{i}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-container">
                    <select class="order-item center" form="request_form" name="item_id">
                    </select>
                </div>
                <div class="input-container">
                    <input class="order-submit center" type="submit" value="Submit Order"/>
                </div>
            </form>
        </div>
        <div class="floor">
            <div class="current-floor">All<span> Floors</span></div>
            <button class="choose-floor-button">Choose floor</button>
            <img class="grid-toggle" src="{% static "images/grid.png" %}">
        </div>
        <div class="choose-floor center">
            <select class="requests-floor center">
                <option>Select a floor</option>
                {% for i in floor_options %}
                    <option>{{i}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="all-orders">
            {% for request in active_requests %}
                <div class="order-container">
                    <div class="order-details">
                        <div class="what">{{request.item.item.name}}</div>
                        <div class="who">{{request.requester.full_name}} - located at: {{request.employee_location}}</div>
                    </div>
                    <img class="complete-icon" src="{% static "images/check.png" %}">
                </div>
            {% endfor %}
        </div>
        <button class="new-order">+</button>
        
        <!-- JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="{% static "js/scripts.js" %}"></script>
    </body>
</html>